services:
  faster-whisper-loader:
    platform: linux/amd64
    build:
      context: faster
      dockerfile: Dockerfile.loader
    container_name: faster-whisper-loader
    entrypoint: /bin/sh -c 'python load_models.py'
    volumes:
      - ./faster/models:/app/models

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    restart: unless-stopped
    networks:
      - isolated

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=transcriptions_db
#      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
#      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
#      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
#      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    networks:
      - isolated
      - net
    depends_on:
      - mongo
    ports:
      - "8888:8081"

  faster-whisper:
    platform: linux/amd64
    build: faster
    container_name: faster-whisper
    ports:
      - "10300:5000"
    volumes:
      - ./faster/uploads:/app/uploads
      - ./faster/models:/app/models
      - ./faster/transcriptions:/app/transcriptions
      - ./faster/transcript.py:/app/transcript.py
    restart: unless-stopped
    networks:
      - isolated
      - net
    depends_on:
      - mongo
      - faster-whisper-loader


  app:
    platform: linux/amd64
    build: ui
    ports:
      - "8080:80"
    container_name: app
    restart: unless-stopped
    networks:
      - net
      - isolated
    depends_on:
      - faster-whisper

networks:
  isolated:
    internal: true
  net:
    driver: bridge